# Generated by Django 2.0.7 on 2018-11-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_connection', '0002_auto_20181119_1202'),
        ('main', '0011_auto_20181120_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ofType', models.CharField(max_length=10)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('icon', models.ForeignKey(blank=True, default=None, on_delete='PROTECTED', to='app_services.Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.ForeignKey(default=None, on_delete='PROTECTED', to='app_services.Icon')),
            ],
        ),
        migrations.CreateModel(
            name='MissingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('query', 'Consulta sql'), ('directory', 'Directorio'), ('map', 'Mapa'), ('catalog', 'Catalogo')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofType', models.CharField(choices=[('menu', 'Menu'), ('button', 'Botón')], max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete='PROTECTED', to='app_services.Container')),
                ('groups', models.ManyToManyField(blank=True, to='main.Group')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
            },
        ),
        migrations.CreateModel(
            name='SQLQuery',
            fields=[
                ('service', models.OneToOneField(limit_choices_to={'kind': 'query'}, on_delete='CASCADE', primary_key=True, related_name='query', related_query_name='query', serialize=False, to='app_services.Service')),
                ('type_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('query_sql', models.CharField(blank=True, max_length=300)),
                ('theme', models.CharField(blank=True, choices=[('generic', 'Generico'), ('directory', 'Directorio')], max_length=20)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ForeignKey(on_delete='PROTECTED', to='app_services.Icon'),
        ),
        migrations.AddField(
            model_name='office',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'directory'}, on_delete='CASCADE', related_name='offices', related_query_name='office', to='app_services.Service'),
        ),
        migrations.AddField(
            model_name='missingitem',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'catalog'}, on_delete='CASCADE', related_name='items', related_query_name='item', to='app_services.Service'),
        ),
        migrations.AddField(
            model_name='menu',
            name='services',
            field=models.ManyToManyField(to='app_services.Service'),
        ),
        migrations.AddField(
            model_name='menu',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'menu'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
        migrations.AddField(
            model_name='location',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'map'}, on_delete='CASCADE', related_name='locations', related_query_name='location', to='app_services.Service'),
        ),
        migrations.AddField(
            model_name='button',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_services.Service'),
        ),
        migrations.AddField(
            model_name='button',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'button'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
        migrations.AddField(
            model_name='field',
            name='sql_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app_services.SQLQuery'),
        ),
    ]
