# Generated by Django 2.0.7 on 2018-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='group',
            field=models.ForeignKey(on_delete='PROTECTED', to='main.Group'),
        ),
    ]
