# Generated by Django 2.1.3 on 2018-11-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('icon', models.ForeignKey(on_delete='PROTECTED', to='app_services.Icon')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(related_name='get_services', to='app_services.Group'),
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete='CASCADE', to='app_services.Menu'),
        ),
        migrations.AddField(
            model_name='item',
            name='service',
            field=models.ForeignKey(on_delete='CASCADE', to='app_services.Service'),
        ),
    ]
