# Generated by Django 2.0.7 on 2018-11-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='services',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_services.Service'),
        ),
        migrations.AlterField(
            model_name='button',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'button'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'menu'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
    ]
