# Generated by Django 2.0.7 on 2018-11-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_auto_20181117_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='services',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_services.Service'),
        ),
    ]
