# Generated by Django 2.1.3 on 2018-11-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_auto_20181113_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('icon', models.ForeignKey(on_delete='PROTECTED', to='app_services.Icon')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_services.Service')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='item',
            name='service',
        ),
        migrations.AddField(
            model_name='menu',
            name='service',
            field=models.ManyToManyField(to='app_services.Service'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
