# Generated by Django 2.0.7 on 2018-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0003_auto_20181117_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='services',
        ),
        migrations.AddField(
            model_name='button',
            name='services',
            field=models.ManyToManyField(to='app_services.Service'),
        ),
    ]
