# Generated by Django 2.1.3 on 2018-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0003_auto_20181113_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='service',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='button',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='button',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='service',
            name='state',
        ),
        migrations.AddField(
            model_name='button',
            name='groups',
            field=models.ManyToManyField(to='app_services.Group'),
        ),
        migrations.AddField(
            model_name='button',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(to='app_services.Group'),
        ),
        migrations.AlterField(
            model_name='button',
            name='service',
            field=models.OneToOneField(on_delete='CASCADE', to='app_services.Service'),
        ),
    ]
