# Generated by Django 2.1.3 on 2018-11-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0004_auto_20181114_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='services',
            new_name='service',
        ),
    ]
