# Generated by Django 2.0.7 on 2018-11-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0005_auto_20181120_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete='PROTECTED', to='main.Group'),
        ),
    ]
