# Generated by Django 2.0.7 on 2018-11-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0005_auto_20181114_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
