# Generated by Django 2.0.7 on 2018-11-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0005_auto_20181117_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_services.Service')),
                ('widget', models.OneToOneField(limit_choices_to={'ofType': 'button'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget')),
            ],
        ),
    ]
