# Generated by Django 2.0.7 on 2018-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '__first__'),
        ('app_services', '0006_auto_20181114_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='groups',
            field=models.ManyToManyField(to='app_admin.Group'),
        ),
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(to='app_admin.Group'),
        ),
    ]
