# Generated by Django 2.0.7 on 2018-11-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0006_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='container',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
