# Generated by Django 2.0.7 on 2018-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181120_0939'),
        ('app_services', '0006_auto_20181120_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='group',
        ),
        migrations.AddField(
            model_name='widget',
            name='group',
            field=models.ManyToManyField(to='main.Group'),
        ),
    ]
