# Generated by Django 2.0.7 on 2018-11-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0007_auto_20181117_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='services',
        ),
        migrations.RemoveField(
            model_name='button',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='services',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='icon',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
