# Generated by Django 2.0.7 on 2018-11-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0007_auto_20181120_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='group',
            new_name='groups',
        ),
    ]
