# Generated by Django 2.0.7 on 2018-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0007_auto_20181114_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sql_auth', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='button',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='groups',
        ),
    ]
