# Generated by Django 2.0.7 on 2018-11-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0008_auto_20181117_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ManyToManyField(to='app_services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofType', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('state', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('container', models.ForeignKey(on_delete='PROTECTED', to='app_services.Container')),
                ('icon', models.ForeignKey(on_delete='PROTECTED', to='app_services.Icon')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'menu'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
        migrations.AddField(
            model_name='button',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'button'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
    ]
