# Generated by Django 2.0.7 on 2018-11-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0009_auto_20181120_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='service',
            field=models.OneToOneField(limit_choices_to={'kind': 'generic'}, on_delete='CASCADE', primary_key=True, related_name='query', related_query_name='query', serialize=False, to='app_services.Service'),
        ),
    ]
