# Generated by Django 2.0.7 on 2018-11-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0009_auto_20181114_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='groups',
        ),
    ]
