# Generated by Django 2.0.7 on 2018-11-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0010_auto_20181120_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='kind',
        ),
        migrations.AddField(
            model_name='service',
            name='ofType',
            field=models.CharField(choices=[('generic', 'Generico'), ('directory', 'Directorio')], default=None, max_length=20),
        ),
    ]
