# Generated by Django 2.0.7 on 2018-11-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0011_auto_20181117_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='services',
            new_name='service',
        ),
    ]
