# Generated by Django 2.0.7 on 2018-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0011_auto_20181120_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ofType',
            field=models.CharField(choices=[('generic', 'Generico'), ('directory', 'Directorio')], max_length=20),
        ),
    ]
