# Generated by Django 2.0.7 on 2018-11-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0012_auto_20181117_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
