# Generated by Django 2.0.7 on 2018-11-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0012_auto_20181120_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ofType',
            new_name='kind',
        ),
    ]
