# Generated by Django 2.0.7 on 2018-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0013_auto_20181117_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='ofType',
            field=models.CharField(choices=[('menu', 'Menu'), ('button', 'Botón')], max_length=20),
        ),
    ]
