# Generated by Django 2.0.7 on 2018-11-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0013_auto_20181114_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='menu',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
