# Generated by Django 2.0.7 on 2018-11-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0013_auto_20181120_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='theme',
            field=models.CharField(choices=[('generic', 'Generico'), ('directory', 'Directorio')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.CharField(choices=[('query', 'Generico'), ('directory', 'Directorio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='service',
            field=models.OneToOneField(limit_choices_to={'kind': 'query'}, on_delete='CASCADE', primary_key=True, related_name='query', related_query_name='query', serialize=False, to='app_services.Service'),
        ),
    ]
