# Generated by Django 2.0.7 on 2018-11-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0014_auto_20181120_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='connection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection'),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='query_sql',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='theme',
            field=models.CharField(blank=True, choices=[('generic', 'Generico'), ('directory', 'Directorio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='type_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
