# Generated by Django 2.0.7 on 2018-11-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0015_auto_20181117_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'button'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
    ]
