# Generated by Django 2.0.7 on 2018-11-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0016_auto_20181117_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'menu'}, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='app_services.Widget'),
        ),
    ]
