# Generated by Django 2.0.7 on 2018-11-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0016_auto_20181120_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='title',
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.CharField(choices=[('query', 'Consulta sql'), ('directory', 'Directorio')], max_length=20),
        ),
    ]
