# Generated by Django 2.1.3 on 2018-11-23 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0021_auto_20181120_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='widget',
            field=models.OneToOneField(limit_choices_to={'ofType': 'menu'}, on_delete=django.db.models.deletion.CASCADE, to='app_services.Widget'),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection'),
        ),
    ]
