# Generated by Django 2.0.7 on 2018-11-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0022_auto_20181122_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='sql_query',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
