# Generated by Django 2.0.7 on 2018-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0023_auto_20181122_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ofType', models.CharField(max_length=10)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
    ]
