# Generated by Django 2.0.7 on 2018-11-23 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0024_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection'),
        ),
    ]
