# Generated by Django 2.0.7 on 2018-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0027_auto_20181122_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
