# Generated by Django 2.1.4 on 2018-12-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('config', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('ofType', models.CharField(max_length=10)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('icon', models.ForeignKey(default=None, on_delete='PROTECTED', to='config.Icon')),
            ],
        ),
        migrations.CreateModel(
            name='MissingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('extension', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('theme', models.CharField(choices=[('generic', 'Generico'), ('directory', 'Directorio'), ('map', 'Mapa'), ('catalog', 'Catalogo')], max_length=20)),
                ('state', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('sql', 'Consulta SQL'), ('model', 'Manual')], max_length=20)),
                ('type_name', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SQLQuery',
            fields=[
                ('service', models.OneToOneField(limit_choices_to={'source': 'sql'}, on_delete='CASCADE', primary_key=True, related_name='query', related_query_name='query', serialize=False, to='services.Service')),
                ('query_sql', models.CharField(blank=True, max_length=300)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='folder',
            field=models.ForeignKey(on_delete='PROTECTED', related_name='services', to='config.Folder'),
        ),
        migrations.AddField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_set', to='main.DBGroup'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ForeignKey(on_delete='PROTECTED', to='config.Icon'),
        ),
        migrations.AddField(
            model_name='office',
            name='service',
            field=models.ForeignKey(limit_choices_to={'theme': 'directory'}, on_delete='CASCADE', related_name='offices', related_query_name='office', to='services.Service'),
        ),
        migrations.AddField(
            model_name='missingitem',
            name='service',
            field=models.ForeignKey(limit_choices_to={'theme': 'catalog'}, on_delete='CASCADE', related_name='items', related_query_name='item', to='services.Service'),
        ),
        migrations.AddField(
            model_name='location',
            name='service',
            field=models.ForeignKey(limit_choices_to={'theme': 'map'}, on_delete='CASCADE', related_name='locations', related_query_name='location', to='services.Service'),
        ),
        migrations.AddField(
            model_name='field',
            name='sql_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='services.SQLQuery'),
        ),
    ]
