# Generated by Django 2.0.7 on 2018-11-11 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_connection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_admin', '0005_auto_20181108_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sql_auth', models.CharField(max_length=300)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(related_name='get_users', to='app_admin.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usergroups',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
    ]
