# Generated by Django 2.0.7 on 2018-11-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_auto_20181111_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.Group'),
        ),
    ]
