# Generated by Django 2.0.7 on 2018-11-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_auto_20181111_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ManyToManyField(to='app_admin.Group'),
        ),
    ]
