# Generated by Django 2.0.7 on 2018-11-11 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_admin', '0010_auto_20181111_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_admin.Group'),
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
