# Generated by Django 2.0.7 on 2018-11-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0013_auto_20181111_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sql_auth',
            field=models.TextField(),
        ),
    ]
