# Generated by Django 2.0.7 on 2018-11-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0014_auto_20181111_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slq_get_user',
            field=models.TextField(blank=True),
        ),
    ]
