# Generated by Django 2.0.7 on 2018-11-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_connection', '0001_initial'),
        ('app_admin', '0015_group_slq_get_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sql_auth', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection')),
            ],
            options={
                'verbose_name': 'Authentication',
                'verbose_name_plural': 'Authentications',
            },
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sql_auth',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.AddField(
            model_name='group',
            name='authentication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_admin.Authentication'),
        ),
    ]
