# Generated by Django 2.0.7 on 2018-11-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0017_auto_20181112_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slq_get_user',
            new_name='sql_get_user',
        ),
    ]
