# Generated by Django 2.1.4 on 2018-12-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationDB',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('table_users', models.CharField(blank=True, max_length=30)),
                ('field_username', models.CharField(blank=True, max_length=30)),
                ('field_password', models.CharField(blank=True, max_length=30)),
                ('connection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection')),
            ],
            options={
                'verbose_name': 'AuthenticationDB',
                'verbose_name_plural': 'AuthenticationDB',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLDAP',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('SERVER_URI', models.CharField(blank=True, max_length=100)),
                ('USER_DN_TEMPLATE', models.CharField(blank=True, max_length=100)),
                ('GROUP_SEARCH', models.CharField(blank=True, max_length=100)),
                ('PERMIT_EMPTY_PASSWORD', models.BooleanField(default=False)),
                ('REQUIRE_GROUP', models.CharField(blank=True, max_length=100)),
                ('DENY_GROUP', models.CharField(blank=True, max_length=100)),
                ('authentication', models.CharField(choices=[('1', 'Enlace directo'), ('2', 'Busqueda/Enlace')], default='1', max_length=20)),
            ],
            options={
                'verbose_name': 'AuthenticationLDAP',
                'verbose_name_plural': 'AuthenticationLDAP',
            },
        ),
        migrations.CreateModel(
            name='DBGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sql_get_user', models.TextField(blank=True)),
                ('connection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection')),
            ],
            options={
                'verbose_name': 'DBGroup',
                'verbose_name_plural': 'DBGroups',
            },
        ),
        migrations.CreateModel(
            name='LDAPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'LDAPGroup',
                'verbose_name_plural': 'LDAPGroups',
            },
        ),
        migrations.CreateModel(
            name='LDAPUserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_SEARCH', models.CharField(max_length=100)),
                ('filter_attr', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'LDAPSearch',
                'verbose_name_plural': 'LDAPSearchs',
            },
        ),
    ]
