# Generated by Django 2.1.4 on 2018-12-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPGroupUserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_SEARCH', models.CharField(max_length=100)),
                ('filter_attr', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'LDAPGroupUserSearch',
                'verbose_name_plural': 'LDAPGroupUserSearchs',
            },
        ),
        migrations.RenameField(
            model_name='dbgroup',
            old_name='sql_get_user',
            new_name='sql_check_user',
        ),
        migrations.RemoveField(
            model_name='dbgroup',
            name='connection',
        ),
        migrations.AddField(
            model_name='ldapgroup',
            name='USER_DN_TEMPLATE',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ldapgroup',
            name='type_bind',
            field=models.CharField(choices=[('1', 'Enlace directo'), ('2', 'Busqueda/Enlace')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='ldapgroupusersearch',
            name='ldapgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LDAPGroup'),
        ),
    ]
