# Generated by Django 2.0.7 on 2018-11-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='connection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection'),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='sql_auth',
            field=models.TextField(blank=True),
        ),
    ]
