# Generated by Django 2.1.4 on 2018-12-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181223_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapgroupusersearch',
            old_name='USER_SEARCH',
            new_name='dn_base',
        ),
        migrations.AlterField(
            model_name='ldapgroup',
            name='type_bind',
            field=models.CharField(choices=[(1, 'Enlace directo'), (2, 'Busqueda/Enlace')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='ldapgroupusersearch',
            name='ldapgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search', to='main.LDAPGroup'),
        ),
    ]
