# Generated by Django 2.0.7 on 2018-11-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181119_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='id',
        ),
        migrations.AlterField(
            model_name='authentication',
            name='name',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
