# Generated by Django 2.0.7 on 2018-11-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_connection', '0002_auto_20181119_1202'),
        ('main', '0008_remove_group_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='connection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection'),
        ),
    ]
