# Generated by Django 2.1.4 on 2018-12-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('type_name', models.CharField(blank=True, max_length=20, unique=True)),
                ('dbgroup', models.ManyToManyField(blank=True, to='main.DBGroup')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete='PROTECTED', related_name='folders', to='config.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='icon',
            field=models.ForeignKey(default=None, on_delete='PROTECTED', to='config.Icon'),
        ),
    ]
