# Generated by Django 2.0.7 on 2018-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='host',
            field=models.CharField(max_length=100),
        ),
    ]
